uses collab.cwl instead of json; bashscript

diff --git a/dockstore-client/bin/dockstore b/dockstore-client/bin/dockstore
--- a/dockstore-client/bin/dockstore
+++ b/dockstore-client/bin/dockstore
@@ -1,2 +1,258 @@
-#!/bin/bash
-echo "HELLO WORLD"
+#!/usr/bin/env bash
+set -o errexit
+
+# Ensure this file is executable via `chmod a+x dockstore`, then place it
+# somewhere on your $PATH, like ~/bin. The rest of SeqWare will be
+# installed upon first run into the ~/.dockstore directory.
+
+DEFAULT_DOCKSTORE_VERSION="${project.version}"
+
+export DOCKSTORE_VERSION="${DOCKSTORE_VERSION:-"$DEFAULT_DOCKSTORE_VERSION"}"
+
+case $DOCKSTORE_VERSION in
+    *SNAPSHOT) SNAPSHOT="YES" ;;
+    *) SNAPSHOT="NO" ;;
+esac
+
+if [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "msys" ]]; then
+    delimiter=";"
+else
+    delimiter=":"
+fi
+
+if [[ "$OSTYPE" == "cygwin" ]]; then
+    cygwin=true
+else
+    cygwin=false
+fi
+
+if [ `id -u` -eq 0 ] && [ "$DOCKSTORE_ROOT" = "" ]; then
+    echo "WARNING: You're currently running as root; probably by accident."
+    echo "Press control-C to abort or Enter to continue as root."
+    echo "Set DOCKSTORE_ROOT to disable this warning."
+    read _
+fi
+
+# export DOCKSTORE_HOME="${DOCKSTORE_HOME:-"$HOME/.dockstore"}"
+export DOCKSTORE_HOME="${DOCKSTORE_HOME:-"$HOME/dockstore"}"
+
+if $cygwin; then
+    export DOCKSTORE_HOME=`cygpath -w "$DOCKSTORE_HOME"`
+fi
+
+# export DOCKSTORE_JAR="$DOCKSTORE_HOME/self-installs/dockstore-client-$DOCKSTORE_VERSION.jar"
+export DOCKSTORE_JAR="$DOCKSTORE_HOME/dockstore-client/target/dockstore-client-$DOCKSTORE_VERSION.jar"
+export DOCKSTORE_SETTINGS="${DOCKSTORE_SETTINGS:-"$DOCKSTORE_HOME/config"}"
+
+# normalize $0 on certain BSDs
+if [ "$(dirname "$0")" = "." ]; then
+    SCRIPT="$(which $(basename "$0"))"
+else
+    SCRIPT="$0"
+fi
+
+# resolve symlinks to the script itself portably
+while [ -h "$SCRIPT" ] ; do
+    ls=`ls -ld "$SCRIPT"`
+    link=`expr "$ls" : '.*-> \(.*\)$'`
+    if expr "$link" : '/.*' > /dev/null; then
+        SCRIPT="$link"
+    else
+        SCRIPT="$(dirname "$SCRIPT"$)/$link"
+    fi
+done
+
+function make_native_path {
+    # ensure we have native paths
+    if $cygwin && [[ "$1"  == /* ]]; then
+    echo -n "$(cygpath -wp "$1")"
+    elif [[ "$OSTYPE" == "msys" && "$1"  == /* ]]; then
+    echo -n "$(sh -c "(cd $1 2</dev/null && pwd -W) || echo $1 | sed 's/^\\/\([a-z]\)/\\1:/g'")"
+    else
+    echo -n "$1"
+    fi
+}
+
+#  usage : add_path PATH_VAR [PATH]...
+function add_path {
+    local path_var="$1"
+    shift
+    while [ -n "$1" ];do
+        # http://bashify.com/?Useful_Techniques:Indirect_Variables:Indirect_Assignment
+    export ${path_var}="${!path_var}${delimiter}$(make_native_path "$1")"
+    shift
+    done
+}
+
+add_path CLASSPATH "$DOCKSTORE_JAR"
+
+BOOTCLASSPATH="-Xbootclasspath/a:$DOCKSTORE_JAR"
+
+# if [ ! -r "$DOCKSTORE_JAR" -a "$1" != "self-install" -a "$1" != "self-check-install" -a "$1" != "init" ]; then
+#     "$0" self-install
+#     if [ $? != 0 ]; then
+#         exit $?
+#     fi
+# fi
+
+# if [ ! -r "$DOCKSTORE_SETTINGS" -a "$1" != "self-install" -a "$1" != "self-check-install"  -a "$1" != "init" ]; then
+#     "$0" init
+#     exit $?
+# fi
+
+# if [ "$HTTP_CLIENT" = "" ]; then
+#     if type -p curl >/dev/null 2>&1; then
+#         if [ "$https_proxy" != "" ]; then
+#             CURL_PROXY="-x $https_proxy"
+#         fi
+#         HTTP_CLIENT="curl $CURL_PROXY -f -L -o"
+#     else
+#         HTTP_CLIENT="wget -O"
+#     fi
+# fi
+
+# TODO: explain what to do when Java is missing
+export JAVA_CMD="${JAVA_CMD:-"java"}"
+
+# Support $JAVA_OPTS for backwards-compatibility.
+export JVM_OPTS="${JVM_OPTS:-"$JAVA_OPTS"}"
+
+# Handle jline issue with cygwin not propagating OSTYPE through java subprocesses: https://github.com/jline/jline2/issues/62
+cygterm=false
+if $cygwin; then
+    case "$TERM" in
+        rxvt* | xterm* | vt*) cygterm=true ;;
+    esac
+fi
+
+if $cygterm; then
+    JVM_OPTS="$JVM_OPTS -Djline.terminal=jline.UnixTerminal"
+    stty -icanon min 1 -echo > /dev/null 2>&1
+fi
+
+function download_failed_message {
+    echo "Failed to download $1"
+    echo "It's possible your HTTP client's certificate store does not have the"
+    echo "correct certificate authority needed. This is often caused by an"
+    echo "out-of-date version of libssl. Either upgrade it or set HTTP_CLIENT"
+    echo "to turn off certificate checks:"
+    echo "  export HTTP_CLIENT=\"wget --no-check-certificate -O\" # or"
+    echo "  export HTTP_CLIENT=\"curl --insecure -f -L -o\""
+    echo "It's also possible that you're behind a firewall haven't yet"
+    echo "set HTTP_PROXY and HTTPS_PROXY."
+}
+
+
+if [ "$1" = "self-install" ]; then
+    if [ -r "$DOCKSTORE_JAR" ]; then
+        echo "The self-install jar already exists at $DOCKSTORE_JAR."
+        echo "If you wish to re-download, delete it and rerun \"$0 self-install\"."
+        exit 1
+    fi
+
+    echo "Downloading Dockstore to $DOCKSTORE_JAR now..."
+    mkdir -p "$(dirname "$DOCKSTORE_JAR")"
+    
+    if [ $SNAPSHOT = "YES" ]; then
+        DOCKSTORE_URL="file:///$HOME/.m2/repository/io/dockstore/dockstore-client/$DOCKSTORE_VERSION/dockstore-client-$DOCKSTORE_VERSION.jar"
+    elif [ -r "/$HOME/.m2/repository/io/dockstore/dockstore-client/$DOCKSTORE_VERSION/dockstore-client-$DOCKSTORE_VERSION.jar" ]; then
+    # for testing, if you have a local release version, just use it
+        DOCKSTORE_URL="file:///$HOME/.m2/repository/io/dockstore/dockstore-client/$DOCKSTORE_VERSION/dockstore-client-$DOCKSTORE_VERSION.jar"
+    else
+        DOCKSTORE_URL="http://wrench.res.oicr.on.ca/artifactory/seqware-release/io/dockstore/dockstore-client/$DOCKSTORE_VERSION/dockstore-client-$DOCKSTORE_VERSION.jar"
+    fi
+
+    $HTTP_CLIENT "$DOCKSTORE_JAR.pending" "$DOCKSTORE_URL"
+    if [ $? == 0 ]; then
+        # TODO: checksum
+        mv -f "$DOCKSTORE_JAR.pending" "$DOCKSTORE_JAR"
+    else
+        rm "$DOCKSTORE_JAR.pending" 2> /dev/null
+        download_failed_message "$DOCKSTORE_URL"
+        exit 1
+    fi
+elif [ "$1" = "init" ]; then
+    if [ -r "$DOCKSTORE_SETTINGS" ]; then
+        echo "The Dockstore settings file already exists at $DOCKSTORE_SETTINGS."
+        echo "If you wish to re-initialize, delete it and rerun \"$0 init\"."
+        exit 1
+    fi
+    
+    mkdir -p "$(dirname "$DOCKSTORE_SETTINGS")"
+    touch $DOCKSTORE_SETTINGS
+    chmod 600 $DOCKSTORE_SETTINGS
+    
+#    echo "# For full details of the available configuration entries, see:" >> $DOCKSTORE_SETTINGS
+#    echo "# http://dockstore.io/docs/6-pipeline/user-configuration/" >> $DOCKSTORE_SETTINGS
+#    echo >> $DOCKSTORE_SETTINGS
+#    echo "# SeqWare MetaDB communication method, can be one of: database, webservice, or none" >> $DOCKSTORE_SETTINGS
+#    echo "SW_METADATA_METHOD=webservice" >> $DOCKSTORE_SETTINGS
+    echo "[webservice]" >> $DOCKSTORE_SETTINGS
+    
+    echo
+    echo "Initializing Dockstore settings:"
+    echo -n "  Dockstore WebService URL: "
+    read WEBSERVICE_URL
+    echo >> $DOCKSTORE_SETTINGS
+    echo "bash_path=$WEBSERVICE_URL" >> $DOCKSTORE_SETTINGS
+    
+    echo -n "  Dockstore token: "
+    read WEBSERVICE_USERNAME
+    echo "token=$WEBSERVICE_USERNAME" >> $DOCKSTORE_SETTINGS
+    
+    echo
+    echo "Created Dockstore settings file at $DOCKSTORE_SETTINGS"
+    echo
+    echo "Dockstore is ready to use!"
+    
+elif [ "$1" = "upgrade" ]; then
+    if [ $SNAPSHOT = "YES" ]; then
+        echo "The upgrade task is only meant for stable releases."
+        exit 1
+    fi
+    if [ ! -w "$SCRIPT" ]; then
+        echo "You do not have permission to upgrade the installation in $SCRIPT"
+        exit 1
+    else
+        TARGET_VERSION="${2:-stable}"
+        echo "The script at $SCRIPT will be upgraded to the latest $TARGET_VERSION version."
+        echo -n "Do you want to continue [Y/n]? "
+        read RESP
+        case "$RESP" in
+            y|Y|"")
+                echo
+                echo "Upgrading..."
+                TARGET="/tmp/dockstore-$$-upgrade"
+                if $cygwin; then
+                    TARGET=`cygpath -w $TARGET`
+                fi
+                DOCKSTORE_SCRIPT_URL="https://TODO/$TARGET_VERSION/bin/dockstore"
+                $HTTP_CLIENT "$TARGET" "$DOCKSTORE_SCRIPT_URL"
+                if [ $? == 0 ]; then
+                    mv "$TARGET" "$SCRIPT" \
+                        && chmod +x "$SCRIPT" \
+                        && echo && "$SCRIPT" self-install \
+                        && echo && echo "Now running" `$SCRIPT version`
+                    exit $?
+                else
+                    download_failed_message "$DOCKSTORE_SCRIPT_URL"
+                fi;;
+            *)
+                echo "Aborted."
+                exit 1;;
+        esac
+    fi
+elif [ "$1" = "version" -o "$1" = "-v" -o "$1" = "--version" ]; then
+# if [ "$1" = "version" -o "$1" = "-v" -o "$1" = "--version" ]; then
+    echo "Dockstore version $DOCKSTORE_VERSION"
+else
+    $JAVA_CMD $DOCKSTORE_JVM_OPTS io.dockstore.client.Client "$@"
+    
+    EXIT_CODE=$?
+
+    if $cygterm ; then
+        stty icanon echo > /dev/null 2>&1
+    fi
+    
+    exit $EXIT_CODE
+fi
